macos:
	clang++ -std=c++17 -o program driver.cpp
gnu:
	g++ -std=c++17 -o program driver.cpp
win:
	g++ -std=c++17 -static-libgcc -static-libstdc++ -o program.exe driver.cpp
debug:
	g++ -std=c++17 -g -o program driver.cpp
clean:
	rm -rf program*
cleaner:
	DEL .\program.exe
